# This workflow builds the NEAR smart contract and runs both unit and integration tests using Rust
# The tests use near-workspaces for comprehensive testing

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev
    
    - name: Install cargo-near
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
    
    - name: Check code formatting
      run: |
        echo "🎨 Checking code formatting..."
        cargo fmt --all -- --check
        echo "✅ Code formatting check passed!"
    
    - name: Build contract
      run: |
        # Run the build script to create the WASM
        ./build.sh
        echo "✅ Contract built successfully!"
        echo "WASM checksum: $(sha256sum target/near/slimedrop.wasm)"
        echo "ABI checksum: $(sha256sum target/near/slimedrop_abi.json)"
    
    - name: Run clippy lints
      run: |
        echo "📋 Running clippy lints..."
        rustup component add clippy
        cargo clippy --target wasm32-unknown-unknown
        echo "✅ Clippy checks passed!"
    
    - name: Run clippy lints on tests
      run: |
        echo "📋 Running clippy lints on tests..."
        rustup component add clippy
        cargo clippy --tests
        echo "✅ Clippy checks passed on tests!"
    
    - name: Run tests
      run: |
        echo "🧪 Running all tests (unit + integration)..."
        cargo test --verbose
        echo "✅ All tests passed!"
    
    - name: Upload WASM artifacts
      uses: actions/upload-artifact@v4
      with:
        name: slimedrop-contract
        path: |
          target/near/slimedrop.wasm
          target/near/slimedrop_abi.json
        retention-days: 30
